### ISSUE TITLE
DebugPanel docs 404

### ISSUE THREAD

**Issue by n-hor** [melonjs/docs#1]
Can't open debugPanel docs. If i use tutorial code, im get error  `me.plugin.register.defer is not a function`

**Comment by obiot** [comment]
although yes it could/should be added, there is no doc indeed for the debugPanel, as it simple as pressing the S key to show/hide it, and then the information in the top panel should be self-explanatory.

also, make sure you are using the latest debugPanel, or at least corresponding with the version of melonJS you are using, based on the error, it looks like you use a outdated version of it.

https://github.com/melonjs/melonJS#download-melonjs
